### ISSUE TITLE
99 Errors

### ISSUE THREAD

**Issue by stefandeclerck** [hlian/jiffy#2]
![screen shot 2015-06-14 at 10 31 42 pm](https://cloud.githubusercontent.com/assets/7692575/8153615/47bc39a2-12e5-11e5-833d-0ea5e8363ca7.png)

**Comment by hlian** [comment]
Yeah this is super old. I'm going to get my shit together this weekend.

**Comment by hlian** [comment]
fixed by https://github.com/hlian/jiffy/commit/b95babd05e57b70b5a4d39a92ca96f5d34caa6d3 ! thanks for reporting
